### ISSUE TITLE
remove depencency on openCV

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/color_balance#2]
OpenCV has some functionality that only operates in 8-bit, which limits color balancing to 8-bit. The functionality of openCV utilized in color balancing (masking out pixels for histogram computation) could be performed using numpy masked arrays. Additionally, color_balancing uses the split() and merge() openCV functions, which can be replaced by numpy indexing, discussed in the opencv docs (http://docs.opencv.org/master/d3/df2/tutorial_py_basic_ops.html)

**Comment by kapadia** [comment]
Done. Lots of opencv calls have been replaced with the numpy api.
